services:

  app:
    build: .
    entrypoint: .docker/entrypoint.sh
    container_name: app_dash_front
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
